/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package InternalFrame;

import Metodos.DAO;
import POJO.Seccion;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 *
 * @author Blutharsch
 */
public final class ActualizarProgramacion extends javax.swing.JInternalFrame {
SessionFactory sf;
Session s;
int Id;
int Id_seccion;

String Anio;
String Seccion;
int Semestre;
int Id_anio;
ButtonGroup g;
/**
     * Creates new form ActualizarProgramacion
     * @param sf
     * @param Id
     * @param Anio
     * @param Seccion
     * @param Semestre
     */
    public ActualizarProgramacion(SessionFactory sf, int Id, String Anio, String Seccion, int Semestre) {
        initComponents();
        g=new ButtonGroup();
        this.sf=sf;
        this.Id=Id;
        this.Anio=Anio;
        this.Seccion=Seccion;
        this.Semestre=Semestre;
        g.add(jRadioButton1);
        g.add(jRadioButton2);
        cbxSecciones();
        cbxAniosAcademicos();
        CargarDatos(Id,Seccion,Anio,Semestre);
    }

    
        public void cbxSecciones() {
        DAO d = new DAO(sf);
        List<Seccion> lista = DAO.CargarSecciones();
        for (Seccion seccion : lista) {
            s = sf.openSession();
            cbxSeccion.addItem(seccion.getNoSeccion());
            s.close();
        }
    }//
    
      public void cbxAniosAcademicos() {
        DAO d = new DAO(sf);
        List<POJO.AnioAcademico> lista = DAO.CargarAnioAcademico();
        for (POJO.AnioAcademico a : lista) {
            s = sf.openSession();
            cbxAnio.addItem(a.getAnio());
            s.close();
        }
    }//
    
       public void ObtenerIdCbx() {
        int n = cbxSeccion.getSelectedIndex()+1;
        DAO d = new DAO(sf);
        Id_seccion = DAO.ObtenerIdSeccion(n).getIdSeccion();
        System.out.println("Seccion: " + Id_seccion);
        
        int n1= cbxAnio.getSelectedIndex()+1;
        Id_anio = DAO.ObtenerIdAnio(n1).getIdAnioAcademico();
        System.out.println("Año: " + Id_anio);
        int semestre=1;
        if(jRadioButton1.isSelected()){ semestre=1;}
        if(jRadioButton2.isSelected()){ semestre=2; }
        
        if(JOptionPane.showConfirmDialog(this, "Actualizar programación para: "+cbxAnio.getSelectedItem().toString()
           +" en la sección "+cbxSeccion.getSelectedItem().toString()
           +"\nSemestre: "+String.valueOf(semestre)+", Inicio: "+TransformDate(),"Confirmar", 
           JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
   
            ActualizarProgramacion(Id, Id_seccion, Id_anio, semestre, TransformDate());
            NuevaProgramacion np= new NuevaProgramacion(sf);
            np.CargarProgramaciones();
            this.dispose();
        }else{return;}
    }//
       
   public String DateChooser(){
   String fechaformato;
   String day= dateChooser.getText().substring(0, 2);
   String month= dateChooser.getText().substring(3,5);
   String year;
   
   if(day.contains("/")){ day=dateChooser.getText().substring(0, 1);}
   if(month.contains("/")){ month= dateChooser.getText().substring(2,4); }
   if(dateChooser.getText().length()==8){ year= dateChooser.getText().substring(6,8); }
   else{ year= dateChooser.getText().substring(5,7);;}
   
   System.out.println(day);
   System.out.println(month);
   System.out.println("20"+year);
   
   fechaformato=day+"/"+month+"/20"+year;
   System.out.println(fechaformato);
  
   return fechaformato;
   }
   
   public Date TransformDate(){
  SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    Date fechaDate = null;
    try {
        fechaDate = formato.parse(DateChooser());     
    } 
    catch (ParseException ex) 
    {
        System.out.println(ex);
    }
    return fechaDate;
   
   }
      
    public void CargarDatos(int Id, String Seccion, String Anio, int Semestre){
    this.txbID.setText(String.valueOf(Id));
    txbID.setEnabled(false);
    cbxSeccion.setSelectedItem(Seccion);
    cbxAnio.setSelectedItem(Anio);
    if(Semestre==1){ jRadioButton1.setSelected(true);}
    if(Semestre==2){ jRadioButton2.setSelected(true);}
    }
    
     public void ActualizarProgramacion(int Id_u, int IdSeccion, int IdAnio, int Semestre, Date Fecha){
     DAO d= new DAO(sf); 
     DAO.EditarProgramacion(Id_u, IdSeccion, IdAnio, Semestre, Fecha);
   }        
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txbID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxSeccion = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbxAnio = new javax.swing.JComboBox();
        dateChooser = new datechooser.beans.DateChooserCombo();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Actualizar información", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel2.setText("Sección");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel3.setText("Año Académico");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel4.setText("Fecha de inicio");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel5.setText("Semestre");

        jRadioButton1.setText("I");

        jRadioButton2.setText("II");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txbID, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(cbxSeccion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxAnio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txbID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/1436251807_Synchronize.png"))); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ObtenerIdCbx();
      
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxAnio;
    private javax.swing.JComboBox cbxSeccion;
    private datechooser.beans.DateChooserCombo dateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField txbID;
    // End of variables declaration//GEN-END:variables
}
