/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package InternalFrame;


import Image.Padding;
import Metodos.DAO;
import Metodos.PaintComponent;
import POJO.Profesor;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 *
 * @author Blutharsch
 */
public final class DirectorioProfesores extends javax.swing.JInternalFrame {
 Padding pad;  
DefaultTableModel dtm=new DefaultTableModel(){
 @Override
 public boolean isCellEditable(int row, int column) {
 return false;
}
};
SessionFactory sf;
Session s;
Icon i;
PaintComponent p;

    /**
     * Creates new form DirectorioProfesores
     */
@Override
 public void paintComponent(Graphics g){
 g.setColor(new Color(255,255,255,64));
 g.fillRect(0, 0, this.getWidth(), this.getHeight());
 }   

 public DirectorioProfesores(SessionFactory sf) {
    initComponents();
    dtm.setColumnIdentifiers(new Object[]{"ID","Nombre del profesor","Apellido","No. cédula", 
                                          "Sexo", "Dirección", "Teléfono", "Usuario"});
    jTable1.setModel(dtm);
    TableRowSorter sorter = new TableRowSorter(dtm);
    jTable1.setRowSorter(sorter);
    this.sf=sf;
    CargarProfesores();
    }
    
    public DirectorioProfesores(){ initComponents(); }
    
    public void CargarProfesores() {
    BufferedImage bi=null;
    LimpiarTabla();
    DAO d= new DAO(sf);
    List<Profesor> p=DAO.Cargar_profesores();
    if(p.isEmpty()){ JOptionPane.showMessageDialog(this, "Lista vacia", "", JOptionPane.INFORMATION_MESSAGE);}
    else{
    for(Profesor pf: p){
    dtm.addRow(new Object[]{pf.getIdProfesor(),pf.getNombre(), pf.getApellido(), pf.getNoCedula(),
                            pf.getSexo(), pf.getDireccion(), pf.getTelefono(), pf.getUsuario()});
    }//for
    }//if
    }//
    
    public void LimpiarTabla(){
    for(int i=dtm.getRowCount()-1;i>=0;i--){
     dtm.removeRow(i);
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        btnBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", "Apellido", "Cédula" }));

        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnBuscarKeyReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/1436254886_Search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jPanel4.setBackground(java.awt.SystemColor.activeCaption);
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/client_account_template.png"))); // NOI18N
        btnEditar.setText("Detalles/Editar");
        btnEditar.setToolTipText("Vista detallada de la información personal del profesor seleccionado");
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/computer_go.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setToolTipText("Regresar al inicio");
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/1436182141_Information.png"))); // NOI18N
        jButton1.setText("Asignaturas");
        jButton1.setToolTipText("Asignaturas que imparte el profesor seleccionado");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
      try{    
        int selectedRow = jTable1.getSelectedRow();
        int Id = Integer.parseInt(String.valueOf(dtm.getValueAt(selectedRow, 0)));
        
        JOptionPane.showMessageDialog(this,""+Id);
        DetallesProfesor dp = new DetallesProfesor(Id, sf, this);

        pad= new Padding();
        
       if(pad.activo(dp, getDesktopPane())){ 
        getDesktopPane().add(dp);
        dp.setVisible(true);
       }else{return;}
        
      }catch(NumberFormatException | HeadlessException | IOException ee){
      JOptionPane.showInternalMessageDialog(this,"Primero seleccione a alguien de la tabla");
      }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      try{
        int seleccionado= jTable1.getSelectedRow();
        int Id=Integer.parseInt(String.valueOf(dtm.getValueAt(seleccionado, 0)));
        String Profesor=String.valueOf(dtm.getValueAt(seleccionado, 1));
        
        DetallesAsignaturas_profesor dap= new DetallesAsignaturas_profesor(Id, sf, Profesor);
         pad= new Padding();
        
       if(pad.activo(dap, getDesktopPane())){ 
        getDesktopPane().add(dap);
        dap.setVisible(true);
       }else{}        
       }catch(NumberFormatException ee){ JOptionPane.showMessageDialog(this,"Primero seleccione un profesor de la tabla");}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarKeyReleased
        // TODO add your handling code here:
     LimpiarTabla();
     s=sf.openSession();
     String opc= jComboBox1.getSelectedItem().toString();
     Criteria c= s.createCriteria(POJO.Profesor.class);   
     
     if(opc.equals("Nombre")){
     int i=0;
     
     for(Object Profesor: c.list()){
     Profesor p= (Profesor) Profesor;
     
     String cad= btnBuscar.getText();
     String buscado= p.getNombre();
     if(buscado.startsWith(cad)||buscado.contains(cad)||buscado.endsWith(cad)){
     dtm.addRow(new Object[]{});
     dtm.setValueAt(p.getIdProfesor(), i, 0);
     dtm.setValueAt(p.getNombre(), i, 1);
     dtm.setValueAt(p.getApellido(), i, 2);
     dtm.setValueAt(p.getNoCedula(), i, 3);
     dtm.setValueAt(p.getSexo(), i, 4);
     dtm.setValueAt(p.getDireccion(), i, 5);
     dtm.setValueAt(p.getTelefono(), i, 6);
     dtm.setValueAt(p.getUsuario(), i, 7);
     i++;
     }
     }
    
     }//
     
     if(opc.equals("Cédula")){
     int i=0;
     
     for(Object Profesor: c.list()){
     Profesor p= (Profesor) Profesor;
     
     String cad= btnBuscar.getText();
     String buscado= p.getNoCedula();
     if(buscado.startsWith(cad)||buscado.contains(cad)||buscado.endsWith(cad)){
     dtm.addRow(new Object[]{});
     dtm.setValueAt(p.getIdProfesor(), i, 0);
     dtm.setValueAt(p.getNombre(), i, 1);
     dtm.setValueAt(p.getApellido(), i, 2);
     dtm.setValueAt(p.getNoCedula(), i, 3);
     dtm.setValueAt(p.getSexo(), i, 4);
     dtm.setValueAt(p.getDireccion(), i, 5);
     dtm.setValueAt(p.getTelefono(), i, 6);
     dtm.setValueAt(p.getUsuario(), i, 7);
     i++;
     }
     }
     }//
     
     if(opc.equals("Apellido")){
     int i=0;
     
     for(Object Profesor: c.list()){
     Profesor p= (Profesor) Profesor;
     
     String cad= btnBuscar.getText();
     String buscado= p.getApellido();
     if(buscado.startsWith(cad)||buscado.contains(cad)||buscado.endsWith(cad)){
     dtm.addRow(new Object[]{});
     dtm.setValueAt(p.getIdProfesor(), i, 0);
     dtm.setValueAt(p.getNombre(), i, 1);
     dtm.setValueAt(p.getApellido(), i, 2);
     dtm.setValueAt(p.getNoCedula(), i, 3);
     dtm.setValueAt(p.getSexo(), i, 4);
     dtm.setValueAt(p.getDireccion(), i, 5);
     dtm.setValueAt(p.getTelefono(), i, 6);
     dtm.setValueAt(p.getUsuario(), i, 7);
     i++;
     }
     }
     }//
     
    }//GEN-LAST:event_btnBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
