/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package InternalFrame;

import Image.Padding;
import Metodos.DAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.hibernate.SessionFactory;

/**
 *
 * @author Blutharsch
 */
public final class NuevoDetalleProgramacion extends javax.swing.JInternalFrame {
DefaultTableModel dtm= new DefaultTableModel(){
 @Override
 public boolean isCellEditable(int row, int column) { return false;}
};

DefaultTableModel dtm1= new DefaultTableModel(){
 @Override
 public boolean isCellEditable(int row, int column) { return false;}
};

SessionFactory sf;
int Id;
String seccion;
String Anio;
String Fecha_inicio;
    /**
     * Creates new form NuevoDetalleProgramacion
     * @param sf
     * @param Id
     * @param Anio
     * @param seccion
     * @param Fecha_inicio
     */
    public NuevoDetalleProgramacion(SessionFactory sf, int Id, String seccion, String Anio, String Fecha_inicio) {
        initComponents();
        this.setTitle("Detalle de programación");
        this.sf=sf;
        this.Id=Id;
        this.seccion=seccion;
        this.Anio=Anio;
        this.Fecha_inicio=Fecha_inicio;
        dtm.setColumnIdentifiers(new Object[]{"ID","Asignatura", "Nombre del profesor", "Apellido",
                                              "Cédula", "Sexo", "Dirección", "Teléfono"});
        dtm1.setColumnIdentifiers(new Object[]{"ID detalle","Asignatura", "Nombre del profesor", "Apellido",
                                              "Cédula", "Sexo", "Dirección", "Teléfono"});
        jTableProfesores_asignaturas.setModel(dtm);
        jTableDetalles.setModel(dtm1);
        
        TableRowSorter rs= new TableRowSorter(dtm);
        jTableProfesores_asignaturas.setRowSorter(rs);
        CargarProfesoresAsignaturas();
        CargarInfoProgramacion();
        CargarDetallesProgramacion(Id);
    }
    
    public NuevoDetalleProgramacion(){initComponents();}

    public void CargarInfoProgramacion(){
    txbID.setEnabled(false);
    txbID.setText(String.valueOf(Id));
    txbSeccion.setEnabled(false);
    txbSeccion.setText(seccion);
    txbAnio.setEnabled(false);
    txbAnio.setText(Anio);
    this.txbFechaIni.setEnabled(false);
    this.txbFechaIni.setText(Fecha_inicio);
    }
    
    public void CargarProfesoresAsignaturas(){
    DAO d= new DAO(sf);
    ArrayList<Object[]> lista= DAO.CargarProfesoresAsignaturas();
    if(lista.isEmpty()){ JOptionPane.showMessageDialog(this,"Lista vacia");}else{
    for (Object[] o: lista) {
     Object[] row= o;
     dtm.addRow(row);
    }
    }
    }
    
    public void CargarDetallesProgramacion(int Id_prog){
    DAO d= new DAO(sf);
    LimpiarTabla();
    ArrayList<Object[]> lista= DAO.CargarDetallesProgramacion(Id_prog);
    if(lista.isEmpty()){ JOptionPane.showMessageDialog(this,"Lista vacia");}else{
    for (Object[] o: lista) {
     Object[] row= o;
     dtm1.addRow(row);
    }
    }
    }
     public void LimpiarTabla(){
    for(int i=dtm1.getRowCount()-1;i>=0;i--){
     dtm1.removeRow(i);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfesores_asignaturas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDetalles = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txbID = new javax.swing.JTextField();
        txbAnio = new javax.swing.JTextField();
        txbSeccion = new javax.swing.JTextField();
        txbFechaIni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jTableProfesores_asignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProfesores_asignaturas);

        jTableDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableDetalles);

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel3.setText("ID Programación");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel4.setText("Año académico");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel5.setText("Sección");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel6.setText("Fecha de inicio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txbAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(txbID))
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txbFechaIni))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(56, 56, 56)
                        .addComponent(txbSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txbID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Detalles de Asignaturas para esta sección");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Profesores y asignaturas");

        jButton1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/add_25.png"))); // NOI18N
        jButton1.setText("Añadir a detalles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/time.png"))); // NOI18N
        jButton2.setText("Ver/EditarHorario");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 497, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE))
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int Id_pro=0;
        try{
        int fila= this.jTableProfesores_asignaturas.getSelectedRow();
        Id_pro= Integer.parseInt(String.valueOf(dtm.getValueAt(fila, 0)));
        
        
        if(JOptionPane.showConfirmDialog(this, "AGREGAR ASIGNATURA DE: "+String.valueOf(dtm.getValueAt(fila, 1))
                +"\nA LA PROGRAMACIÓN DE "+txbAnio.getText()
                +"\nPROFESOR: "+String.valueOf(dtm.getValueAt(fila, 2))+" "+String.valueOf(dtm.getValueAt(fila, 3))
                +"\nInicio del curso "+this.txbFechaIni.getText(),
                "Confirmar cambios", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        
        DAO d= new DAO(sf);
        if(Id_pro!=0){DAO.GuardarDetalle_programacion(Integer.parseInt(txbID.getText()), Id_pro);
        this.CargarDetallesProgramacion(Id);}
        }else{}
        
        }catch(Exception ee){JOptionPane.showMessageDialog(this,"Seleccione a alguien de la tabla "+ee);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      try{
        int selectedRow = jTableDetalles.getSelectedRow();
        /*********************************************************************************************/
        int Id = Integer.parseInt(String.valueOf(dtm1.getValueAt(selectedRow, 0)));
        String Asignatura= String.valueOf(dtm1.getValueAt(selectedRow, 1));
        String Profesor = String.valueOf(dtm1.getValueAt(selectedRow, 2))+" "+String.valueOf(dtm1.getValueAt(selectedRow, 3));
        String A= this.Anio;
        
        Horarios h= new Horarios(sf, Id, Asignatura, Profesor, A);
        Padding pad= new Padding();
        if(pad.activo(h, getDesktopPane())){ 
        getDesktopPane().add(h);
        h.setVisible(true);
        this.dispose();
      }else{JOptionPane.showMessageDialog(this, "Ya hay una ventana de diálogo abierta");}
      }catch(Exception ee){
       JOptionPane.showMessageDialog(this,"Primero seleccione a alguien de la tabla");
    }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDetalles;
    private javax.swing.JTable jTableProfesores_asignaturas;
    private javax.swing.JTextField txbAnio;
    private javax.swing.JTextField txbFechaIni;
    private javax.swing.JTextField txbID;
    private javax.swing.JTextField txbSeccion;
    // End of variables declaration//GEN-END:variables
}
