/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package MDI;


import Image.Padding;
import static Image.Padding.Centrar;
import InternalFrame.AgregarAsignatura;
import InternalFrame.AgregarProfesor;
import InternalFrame.DirectorioProfesores;
import Login.Inicio;
import POJO.CostoMatricula;
import Screensaver.Fondo;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.hibernate.SessionFactory;

/**
 *
 * @author Blutharsch
 */
public class MDI extends javax.swing.JFrame {
SessionFactory sf;
Padding p;
    /**
     * Creates new form MDI
     * @param sf
     */
    public MDI(SessionFactory sf) {
        initComponents();
        this.sf=sf;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        desktopPane.setBorder(new Fondo());
    }
    
    public MDI(){ initComponents(); }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/reseller_programm.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("Directorio");
        fileMenu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/reseller_account.png"))); // NOI18N
        jMenu8.setText("Autoridades");
        jMenu8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem8.setText("Directores");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);

        fileMenu.add(jMenu8);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/ceo.png"))); // NOI18N
        jMenu2.setText("Profesores");
        jMenu2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        openMenuItem.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Ver todos");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(openMenuItem);

        jMenuItem1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem1.setText("Agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        fileMenu.add(jMenu2);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/note_add.png"))); // NOI18N
        jMenuItem2.setText("Asignaturas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem2);
        fileMenu.add(jSeparator2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/user_student.png"))); // NOI18N
        jMenu3.setText("Estudiantes");
        jMenu3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem9.setText("Agregar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem10.setText("Mostrar todos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        fileMenu.add(jMenu3);

        menuBar.add(fileMenu);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/cash_register_2.png"))); // NOI18N
        jMenu1.setText("Matrículas");
        jMenu1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/user_add.png"))); // NOI18N
        jMenuItem11.setText("Nueva matrícula");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        menuBar.add(jMenu1);

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/date_magnify.png"))); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("Programaciones");
        editMenu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/calendar_copy.png"))); // NOI18N
        jMenuItem4.setText("Registro");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem4);

        menuBar.add(editMenu);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/coins.png"))); // NOI18N
        jMenu4.setText("Mensualidades");
        jMenu4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem12.setText("Abonos");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        menuBar.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/attach.png"))); // NOI18N
        jMenu5.setText("Registro Académico");
        jMenu5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        menuBar.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/cog.png"))); // NOI18N
        jMenu6.setText("Configurar");
        jMenu6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem3.setText("Costos de matrícula");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuItem5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem5.setText("Costos de mensualidades");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);
        jMenu6.add(jSeparator1);

        jMenuItem6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem6.setText("Secciones");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        menuBar.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/user.png"))); // NOI18N
        jMenu7.setText("Session");
        jMenu7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/user_delete.png"))); // NOI18N
        jMenuItem7.setText("Cerrar sesión");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        menuBar.add(jMenu7);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        p=new Padding();
        DirectorioProfesores dp= new DirectorioProfesores(sf);
        
        if(p.activo(dp, desktopPane)){
         desktopPane.add(dp);
         dp.setVisible(true); }else{ return; }
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         p=new Padding();
        AgregarProfesor ap= new AgregarProfesor(sf);
        
        if(p.activo(ap, desktopPane)){
         desktopPane.add(ap);
         ap.setVisible(true); }else{ return; }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AgregarAsignatura aa= new AgregarAsignatura(sf);
        p=new Padding();
        
        if(p.activo(aa, desktopPane)){
        desktopPane.add(aa);
        aa.setVisible(true);
       }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        InternalFrame.CostoMatricula cm= new InternalFrame.CostoMatricula(sf);
        p=new Padding();
        
        if(p.activo(cm, desktopPane)){
        desktopPane.add(cm);
        cm.setVisible(true);}
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        InternalFrame.CostoMensualidad cm= new InternalFrame.CostoMensualidad(sf);
        p=new Padding();
        
        if(p.activo(cm, desktopPane)){
        desktopPane.add(cm);
        cm.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Terminar y salir de esta sesión", "Confirmar",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        new Inicio().setVisible(true);
        this.dispose();
        }else{return;}
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        InternalFrame.Secciones secciones= new InternalFrame.Secciones(sf);
        p=new Padding();
        
        if(p.activo(secciones, desktopPane)){
        desktopPane.add(secciones);
        secciones.setVisible(true);
    }//
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
       InternalFrame.NuevaProgramacion np= new InternalFrame.NuevaProgramacion(sf);
       p=new Padding(); 
        if(p.activo(np, desktopPane)){
        Centrar(np, desktopPane);
    }else{JOptionPane.showMessageDialog(this,"Ya existe una ventana de "+jMenuItem4.getText()+" abierta");}//
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
       InternalFrame.VerDirectores v= new InternalFrame.VerDirectores(sf);
       p=new Padding(); 
        if(p.activo(v, desktopPane)){
        Centrar(v, desktopPane);
    }else{JOptionPane.showMessageDialog(this,"Ya existe una ventana de "+jMenuItem8.getText()+" abierta");}//
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
       
       InternalFrame.AgregarEstudiante a= new InternalFrame.AgregarEstudiante(sf);
       p=new Padding(); 
       if(p.activo(a, desktopPane)){
       Centrar(a, desktopPane);
    }else{JOptionPane.showMessageDialog(this,"Ya existe una ventana de Añadir Estudiantes abierta");}//
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
       InternalFrame.VerEstudiantes v= new InternalFrame.VerEstudiantes(sf);
       p=new Padding(); 
       if(p.activo(v, desktopPane)){
       Centrar(v, desktopPane);
    }else{JOptionPane.showMessageDialog(this,"Ya existe una ventana del mismo tipo abierta");}//
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
       InternalFrame.Matriculas m= new InternalFrame.Matriculas(sf);
       p=new Padding(); 
       if(p.activo(m, desktopPane)){
       Centrar(m, desktopPane);
    }else{JOptionPane.showMessageDialog(this,"Ya existe una ventana del mismo tipo abierta");}//
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        InternalFrame.GuardarPagoMensualidad m= new InternalFrame.GuardarPagoMensualidad(sf);
       p=new Padding(); 
       if(p.activo(m, desktopPane)){
       Centrar(m, desktopPane);
    }else{JOptionPane.showMessageDialog(this,"Ya existe una ventana del mismo tipo abierta");}//
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    // End of variables declaration//GEN-END:variables

}
