/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Webcam;

import InternalFrame.AgregarProfesor;
import com.googlecode.javacv.FrameGrabber;
import com.googlecode.javacv.OpenCVFrameGrabber;
import com.googlecode.javacv.VideoInputFrameGrabber;
import com.googlecode.javacv.cpp.opencv_core;
import static com.googlecode.javacv.cpp.opencv_core.cvFlip;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Blutharsch
 */
public final class Camara extends javax.swing.JInternalFrame {
 camara camara;
 public int NumeroCamara = 0;
 public opencv_core.IplImage img;
 public FrameGrabber grabber;
 boolean Flag = true;
 BufferedImage imageV;
 AgregarProfesor ap;
 ImageIcon icon;
 
@Override
protected void paintComponent(Graphics g){
g.setColor(new Color(255,255,255,64));
g.fillRect(0, 0, getWidth(), getHeight());
}
 /**
     * Creates new form Camara
     * @param ap
     */
  public Camara(AgregarProfesor ap){
    initComponents();
    this.CargarCamara();
    this.ap=ap;
    }
    
    public Camara() {
        initComponents();
        this.CargarCamara();
    }
     
    class camara extends Thread {
        @Override
        public void run() {
            MetodoGrabber();
       }
    }
       public static BufferedImage resize(BufferedImage bufferedImage, int newW, int newH) {
        try {
          int w = bufferedImage.getWidth();
          int h = bufferedImage.getHeight();
          
          BufferedImage bufim = new BufferedImage(newW, newH, bufferedImage.getType());
          Graphics2D g = bufim.createGraphics();
          g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
          g.drawImage(bufferedImage, 0, 0, newW, newH, 0, 0, w, h, null);
          g.dispose();
          
          return bufim;
        } catch (NullPointerException n) {  return null; }
    }

    public void MetodoGrabber() {
    try {
        grabber = new OpenCVFrameGrabber(NumeroCamara);
        grabber.start();
      while (Flag) { img = grabber.grab();
            if (img != null) { cvFlip(img, img, 1);}
             icon = new ImageIcon(img.getBufferedImage());
             ImageIcon ic = new ImageIcon(resize(img.getBufferedImage(), 260, 285));
             lblpicture.setIcon(ic);
            }//While
        } catch (FrameGrabber.Exception ex) {
            System.out.println(""+ex.getCause());
        }
    }
    
       public void GuardarMetodoGrabber() {
        try {
            Icon icono = lblpicture.getIcon();
            Redimensionar redimImagen = new Redimensionar();

          if (this.ap != null) {
           icono = redimImagen.imageToIcon(redimImagen.iconToBufferedImage(icono).getScaledInstance(ap.img.getWidth(), ap.img.getHeight(), 0));       
           ap.f=img.getBufferedImage();
           ap.img.setIcon(icono);
           ap.img.setText(null);
          }
          this.CerrarCam();
          this.dispose();
        } catch (Exception e) {
          System.out.println("" + e.getMessage());
          System.out.println("+ " + e.getCause());
          JOptionPane.showMessageDialog(null, "Error al guardar la foto", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
      public void CargarCamara() {
        cbxDriver.removeAllItems();
        String[] Devices = null;
        try {
            Devices = VideoInputFrameGrabber.getDeviceDescriptions();
        } catch (FrameGrabber.Exception ex) {
            JOptionPane.showMessageDialog(null, "No Se Han Encontrado Cámaras Conectadas", "Cámaras No Encontradas", 
            JOptionPane.ERROR_MESSAGE);
            return;}
       
        for (String Dev : Devices) {
         cbxDriver.addItem(Dev);
        }
    }
      
      public void CerrarCam() {
      try {
       Flag = false;
       grabber.release();
        } catch (FrameGrabber.Exception e) {
    }
    }//  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblpicture = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tomar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cbxDriver = new javax.swing.JComboBox();
        btnIni = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/emotion_grin.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.SystemColor.activeCaption));
        jPanel2.setForeground(java.awt.SystemColor.textHighlight);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblpicture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblpicture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tomar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/tick.png"))); // NOI18N
        tomar.setText("Guardar");
        tomar.setHideActionText(true);
        tomar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tomar.setVerifyInputWhenFocusTarget(false);
        tomar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/camera_add.png"))); // NOI18N
        jButton1.setText("Captura");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tomar, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tomar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnIni.setText("Iniciar");
        btnIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIni, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIni)
                    .addComponent(cbxDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniActionPerformed
      if (camara != null) {
            CerrarCam();
            camara.stop();
        }
        Flag = true;
        NumeroCamara = cbxDriver.getSelectedIndex();
        camara = new camara();
        camara.start();
        btnIni.setEnabled(false);
        this.setTitle(""+cbxDriver.getSelectedItem().toString());    
        this.lblpicture.setVisible(true);  
    }//GEN-LAST:event_btnIniActionPerformed

    private void tomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomarActionPerformed
        // TODO add your handling code here:
        if(ap!=null){
        this.GuardarMetodoGrabber();
        }
    }//GEN-LAST:event_tomarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
     try{ this.CerrarCam(); }catch(NullPointerException npe){ this.dispose();}   
    }//GEN-LAST:event_formInternalFrameClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.CerrarCam();
        this.btnIni.setEnabled(true);
        this.btnIni.setText("Tomar otra vez");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIni;
    private javax.swing.JComboBox cbxDriver;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblpicture;
    private javax.swing.JButton tomar;
    // End of variables declaration//GEN-END:variables
}
