package POJO;
// Generated 19-ago-2015 14:32:50 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * AnioAcademico generated by hbm2java
 */
public class AnioAcademico  implements java.io.Serializable {


     private Integer idAnioAcademico;
     private String anio;
     private Set programacions = new HashSet(0);

    public AnioAcademico() {
    }

	
    public AnioAcademico(String anio) {
        this.anio = anio;
    }
    public AnioAcademico(String anio, Set programacions) {
       this.anio = anio;
       this.programacions = programacions;
    }
   
    public Integer getIdAnioAcademico() {
        return this.idAnioAcademico;
    }
    
    public void setIdAnioAcademico(Integer idAnioAcademico) {
        this.idAnioAcademico = idAnioAcademico;
    }
    public String getAnio() {
        return this.anio;
    }
    
    public void setAnio(String anio) {
        this.anio = anio;
    }
    public Set getProgramacions() {
        return this.programacions;
    }
    
    public void setProgramacions(Set programacions) {
        this.programacions = programacions;
    }




}


