package POJO;
// Generated 19-ago-2015 14:32:50 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private Integer idAsignatura;
     private String nombreAsignatura;
     private Set profesorAsignaturas = new HashSet(0);

    public Asignatura() {
    }

    public Asignatura(String nombreAsignatura, Set profesorAsignaturas) {
       this.nombreAsignatura = nombreAsignatura;
       this.profesorAsignaturas = profesorAsignaturas;
    }
   
    public Integer getIdAsignatura() {
        return this.idAsignatura;
    }
    
    public void setIdAsignatura(Integer idAsignatura) {
        this.idAsignatura = idAsignatura;
    }
    public String getNombreAsignatura() {
        return this.nombreAsignatura;
    }
    
    public void setNombreAsignatura(String nombreAsignatura) {
        this.nombreAsignatura = nombreAsignatura;
    }
    public Set getProfesorAsignaturas() {
        return this.profesorAsignaturas;
    }
    
    public void setProfesorAsignaturas(Set profesorAsignaturas) {
        this.profesorAsignaturas = profesorAsignaturas;
    }




}


