package POJO;
// Generated 19-ago-2015 14:32:50 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * DetalleProgramacion generated by hbm2java
 */
public class DetalleProgramacion  implements java.io.Serializable {


     private Integer idDetalleProgramacion;
     private Programacion programacion;
     private ProfesorAsignatura profesorAsignatura;
     private Set horarios = new HashSet(0);

    public DetalleProgramacion() {
    }

    public DetalleProgramacion(Programacion programacion, ProfesorAsignatura profesorAsignatura, Set horarios) {
       this.programacion = programacion;
       this.profesorAsignatura = profesorAsignatura;
       this.horarios = horarios;
    }
   
    public Integer getIdDetalleProgramacion() {
        return this.idDetalleProgramacion;
    }
    
    public void setIdDetalleProgramacion(Integer idDetalleProgramacion) {
        this.idDetalleProgramacion = idDetalleProgramacion;
    }
    public Programacion getProgramacion() {
        return this.programacion;
    }
    
    public void setProgramacion(Programacion programacion) {
        this.programacion = programacion;
    }
    public ProfesorAsignatura getProfesorAsignatura() {
        return this.profesorAsignatura;
    }
    
    public void setProfesorAsignatura(ProfesorAsignatura profesorAsignatura) {
        this.profesorAsignatura = profesorAsignatura;
    }
    public Set getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set horarios) {
        this.horarios = horarios;
    }




}


