package POJO;
// Generated 19-ago-2015 14:32:50 by Hibernate Tools 3.6.0



/**
 * DetallesRegistro generated by hbm2java
 */
public class DetallesRegistro  implements java.io.Serializable {


     private Integer idDetallesRegistro;
     private Registro registro;
     private Float notaFinal;

    public DetallesRegistro() {
    }

    public DetallesRegistro(Registro registro, Float notaFinal) {
       this.registro = registro;
       this.notaFinal = notaFinal;
    }
   
    public Integer getIdDetallesRegistro() {
        return this.idDetallesRegistro;
    }
    
    public void setIdDetallesRegistro(Integer idDetallesRegistro) {
        this.idDetallesRegistro = idDetallesRegistro;
    }
    public Registro getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(Registro registro) {
        this.registro = registro;
    }
    public Float getNotaFinal() {
        return this.notaFinal;
    }
    
    public void setNotaFinal(Float notaFinal) {
        this.notaFinal = notaFinal;
    }




}


