package POJO;
// Generated 19-ago-2015 14:32:50 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private Integer idEstudiante;
     private String noCarnet;
     private String nombre;
     private String apellido;
     private Date fehaNac;
     private String sexo;
     private String direccion;
     private String telefono;
     private byte[] image;
     private int estado;
     private Set matriculas = new HashSet(0);
     private Set pagoMensualidads = new HashSet(0);

    public Estudiante() {
    }

	
    public Estudiante(String nombre, String apellido, Date fehaNac, String sexo, String direccion, byte[] image, int estado) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.fehaNac = fehaNac;
        this.sexo = sexo;
        this.direccion = direccion;
        this.image = image;
        this.estado = estado;
    }
    public Estudiante(String noCarnet, String nombre, String apellido, Date fehaNac, String sexo, String direccion, String telefono, byte[] image, int estado, Set matriculas, Set pagoMensualidads) {
       this.noCarnet = noCarnet;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fehaNac = fehaNac;
       this.sexo = sexo;
       this.direccion = direccion;
       this.telefono = telefono;
       this.image = image;
       this.estado = estado;
       this.matriculas = matriculas;
       this.pagoMensualidads = pagoMensualidads;
    }
   
    public Integer getIdEstudiante() {
        return this.idEstudiante;
    }
    
    public void setIdEstudiante(Integer idEstudiante) {
        this.idEstudiante = idEstudiante;
    }
    public String getNoCarnet() {
        return this.noCarnet;
    }
    
    public void setNoCarnet(String noCarnet) {
        this.noCarnet = noCarnet;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFehaNac() {
        return this.fehaNac;
    }
    
    public void setFehaNac(Date fehaNac) {
        this.fehaNac = fehaNac;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }
    public Set getPagoMensualidads() {
        return this.pagoMensualidads;
    }
    
    public void setPagoMensualidads(Set pagoMensualidads) {
        this.pagoMensualidads = pagoMensualidads;
    }




}


