package POJO;
// Generated 19-ago-2015 14:32:50 by Hibernate Tools 3.6.0



/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private Integer idHorario;
     private DetalleProgramacion detalleProgramacion;
     private String dia;
     private String horaEntrada;
     private String horaSalida;

    public Horario() {
    }

    public Horario(DetalleProgramacion detalleProgramacion, String dia, String horaEntrada, String horaSalida) {
       this.detalleProgramacion = detalleProgramacion;
       this.dia = dia;
       this.horaEntrada = horaEntrada;
       this.horaSalida = horaSalida;
    }
   
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }
    public DetalleProgramacion getDetalleProgramacion() {
        return this.detalleProgramacion;
    }
    
    public void setDetalleProgramacion(DetalleProgramacion detalleProgramacion) {
        this.detalleProgramacion = detalleProgramacion;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public String getHoraEntrada() {
        return this.horaEntrada;
    }
    
    public void setHoraEntrada(String horaEntrada) {
        this.horaEntrada = horaEntrada;
    }
    public String getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(String horaSalida) {
        this.horaSalida = horaSalida;
    }




}


