package POJO;
// Generated 19-ago-2015 14:32:50 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private Integer idMatricula;
     private CostoMatricula costoMatricula;
     private Programacion programacion;
     private Estudiante estudiante;
     private Date fechaMatricula;
     private Set registros = new HashSet(0);

    public Matricula() {
    }

    public Matricula(CostoMatricula costoMatricula, Programacion programacion, Estudiante estudiante, Date fechaMatricula, Set registros) {
       this.costoMatricula = costoMatricula;
       this.programacion = programacion;
       this.estudiante = estudiante;
       this.fechaMatricula = fechaMatricula;
       this.registros = registros;
    }
   
    public Integer getIdMatricula() {
        return this.idMatricula;
    }
    
    public void setIdMatricula(Integer idMatricula) {
        this.idMatricula = idMatricula;
    }
    public CostoMatricula getCostoMatricula() {
        return this.costoMatricula;
    }
    
    public void setCostoMatricula(CostoMatricula costoMatricula) {
        this.costoMatricula = costoMatricula;
    }
    public Programacion getProgramacion() {
        return this.programacion;
    }
    
    public void setProgramacion(Programacion programacion) {
        this.programacion = programacion;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Date getFechaMatricula() {
        return this.fechaMatricula;
    }
    
    public void setFechaMatricula(Date fechaMatricula) {
        this.fechaMatricula = fechaMatricula;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


