package POJO;
// Generated 19-ago-2015 14:32:50 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * PagoMensualidad generated by hbm2java
 */
public class PagoMensualidad  implements java.io.Serializable {


     private Integer idPagomensualidad;
     private CostoMensualidad costoMensualidad;
     private Estudiante estudiante;
     private Date fechaPago;

    public PagoMensualidad() {
    }

    public PagoMensualidad(CostoMensualidad costoMensualidad, Estudiante estudiante, Date fechaPago) {
       this.costoMensualidad = costoMensualidad;
       this.estudiante = estudiante;
       this.fechaPago = fechaPago;
    }
   
    public Integer getIdPagomensualidad() {
        return this.idPagomensualidad;
    }
    
    public void setIdPagomensualidad(Integer idPagomensualidad) {
        this.idPagomensualidad = idPagomensualidad;
    }
    public CostoMensualidad getCostoMensualidad() {
        return this.costoMensualidad;
    }
    
    public void setCostoMensualidad(CostoMensualidad costoMensualidad) {
        this.costoMensualidad = costoMensualidad;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }




}


