package POJO;
// Generated 19-ago-2015 14:32:50 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ProfesorAsignatura generated by hbm2java
 */
public class ProfesorAsignatura  implements java.io.Serializable {


     private Integer idProfesorAsignatura;
     private Asignatura asignatura;
     private Profesor profesor;
     private Set detalleProgramacions = new HashSet(0);

    public ProfesorAsignatura() {
    }

    public ProfesorAsignatura(Asignatura asignatura, Profesor profesor, Set detalleProgramacions) {
       this.asignatura = asignatura;
       this.profesor = profesor;
       this.detalleProgramacions = detalleProgramacions;
    }
   
    public Integer getIdProfesorAsignatura() {
        return this.idProfesorAsignatura;
    }
    
    public void setIdProfesorAsignatura(Integer idProfesorAsignatura) {
        this.idProfesorAsignatura = idProfesorAsignatura;
    }
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public Set getDetalleProgramacions() {
        return this.detalleProgramacions;
    }
    
    public void setDetalleProgramacions(Set detalleProgramacions) {
        this.detalleProgramacions = detalleProgramacions;
    }




}


