package POJO;
// Generated 19-ago-2015 14:32:50 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private Integer idProfesor;
     private String nombre;
     private String apellido;
     private String noCedula;
     private String sexo;
     private byte[] image;
     private String direccion;
     private String telefono;
     private String usuario;
     private String pwd;
     private int estado;
     private Set tituloses = new HashSet(0);
     private Set profesorAsignaturas = new HashSet(0);

    public Profesor() {
    }

	
    public Profesor(String nombre, String apellido, String noCedula, String sexo, byte[] image, String direccion, int estado) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.noCedula = noCedula;
        this.sexo = sexo;
        this.image = image;
        this.direccion = direccion;
        this.estado = estado;
    }
    public Profesor(String nombre, String apellido, String noCedula, String sexo, byte[] image, String direccion, String telefono, String usuario, String pwd, int estado, Set tituloses, Set profesorAsignaturas) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.noCedula = noCedula;
       this.sexo = sexo;
       this.image = image;
       this.direccion = direccion;
       this.telefono = telefono;
       this.usuario = usuario;
       this.pwd = pwd;
       this.estado = estado;
       this.tituloses = tituloses;
       this.profesorAsignaturas = profesorAsignaturas;
    }
   
    public Integer getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(Integer idProfesor) {
        this.idProfesor = idProfesor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNoCedula() {
        return this.noCedula;
    }
    
    public void setNoCedula(String noCedula) {
        this.noCedula = noCedula;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set getTituloses() {
        return this.tituloses;
    }
    
    public void setTituloses(Set tituloses) {
        this.tituloses = tituloses;
    }
    public Set getProfesorAsignaturas() {
        return this.profesorAsignaturas;
    }
    
    public void setProfesorAsignaturas(Set profesorAsignaturas) {
        this.profesorAsignaturas = profesorAsignaturas;
    }




}


