package POJO;
// Generated 19-ago-2015 14:32:50 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Programacion generated by hbm2java
 */
public class Programacion  implements java.io.Serializable {


     private Integer idProgramacion;
     private AnioAcademico anioAcademico;
     private Seccion seccion;
     private int semestre;
     private Date fechaIni;
     private int estado;
     private Set matriculas = new HashSet(0);
     private Set detalleProgramacions = new HashSet(0);

    public Programacion() {
    }

	
    public Programacion(int semestre, int estado) {
        this.semestre = semestre;
        this.estado = estado;
    }
    public Programacion(AnioAcademico anioAcademico, Seccion seccion, int semestre, Date fechaIni, int estado, Set matriculas, Set detalleProgramacions) {
       this.anioAcademico = anioAcademico;
       this.seccion = seccion;
       this.semestre = semestre;
       this.fechaIni = fechaIni;
       this.estado = estado;
       this.matriculas = matriculas;
       this.detalleProgramacions = detalleProgramacions;
    }
   
    public Integer getIdProgramacion() {
        return this.idProgramacion;
    }
    
    public void setIdProgramacion(Integer idProgramacion) {
        this.idProgramacion = idProgramacion;
    }
    public AnioAcademico getAnioAcademico() {
        return this.anioAcademico;
    }
    
    public void setAnioAcademico(AnioAcademico anioAcademico) {
        this.anioAcademico = anioAcademico;
    }
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }
    public int getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(int semestre) {
        this.semestre = semestre;
    }
    public Date getFechaIni() {
        return this.fechaIni;
    }
    
    public void setFechaIni(Date fechaIni) {
        this.fechaIni = fechaIni;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }
    public Set getDetalleProgramacions() {
        return this.detalleProgramacions;
    }
    
    public void setDetalleProgramacions(Set detalleProgramacions) {
        this.detalleProgramacions = detalleProgramacions;
    }




}


