package POJO;
// Generated 19-ago-2015 14:32:50 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Registro generated by hbm2java
 */
public class Registro  implements java.io.Serializable {


     private Integer idRegistro;
     private Matricula matricula;
     private Date fechaRegistro;
     private Set detallesRegistros = new HashSet(0);

    public Registro() {
    }

    public Registro(Matricula matricula, Date fechaRegistro, Set detallesRegistros) {
       this.matricula = matricula;
       this.fechaRegistro = fechaRegistro;
       this.detallesRegistros = detallesRegistros;
    }
   
    public Integer getIdRegistro() {
        return this.idRegistro;
    }
    
    public void setIdRegistro(Integer idRegistro) {
        this.idRegistro = idRegistro;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getDetallesRegistros() {
        return this.detallesRegistros;
    }
    
    public void setDetallesRegistros(Set detallesRegistros) {
        this.detallesRegistros = detallesRegistros;
    }




}


