package POJO;
// Generated 19-ago-2015 14:32:50 by Hibernate Tools 3.6.0



/**
 * Titulos generated by hbm2java
 */
public class Titulos  implements java.io.Serializable {


     private Integer idTitulo;
     private Profesor profesor;
     private String cadTitulo;

    public Titulos() {
    }

    public Titulos(Profesor profesor, String cadTitulo) {
       this.profesor = profesor;
       this.cadTitulo = cadTitulo;
    }
   
    public Integer getIdTitulo() {
        return this.idTitulo;
    }
    
    public void setIdTitulo(Integer idTitulo) {
        this.idTitulo = idTitulo;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public String getCadTitulo() {
        return this.cadTitulo;
    }
    
    public void setCadTitulo(String cadTitulo) {
        this.cadTitulo = cadTitulo;
    }




}


